package org.jsecurity.dao;


import org.jsecurity.entity.MenuDO;

public interface MenuDao {
    /**
     *
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu
     *
     * @mbggenerated Sun Dec 04 18:23:57 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu
     *
     * @mbggenerated Sun Dec 04 18:23:57 CST 2016
     */
    int insert(MenuDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu
     *
     * @mbggenerated Sun Dec 04 18:23:57 CST 2016
     */
    int insertSelective(MenuDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu
     *
     * @mbggenerated Sun Dec 04 18:23:57 CST 2016
     */
    MenuDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu
     *
     * @mbggenerated Sun Dec 04 18:23:57 CST 2016
     */
    int updateByPrimaryKeySelective(MenuDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu
     *
     * @mbggenerated Sun Dec 04 18:23:57 CST 2016
     */
    int updateByPrimaryKey(MenuDO record);
}